kind: Deployment
apiVersion:
  extensions/v1beta1
metadata:
  namespace: demo-03
  name: kdemo-dep
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        name: kdemo
    spec:
      containers:
      - name: kdemo
        image: apprenda/kdemo:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 1
