apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demo-02
  labels:
    name: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
  selector:
    name: frontend
